C:\DEV\01. workspace\korea_wildlife_object_detection\yolov7\train.py:87: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(weights, map_location=device)  # load checkpoint
Traceback (most recent call last):
  File "C:\DEV\01. workspace\korea_wildlife_object_detection\yolov7\train.py", line 616, in <module>
    train(hyp, opt, device, tb_writer)
  File "C:\DEV\01. workspace\korea_wildlife_object_detection\yolov7\train.py", line 88, in train
    model = Model(opt.cfg or ckpt['model'].yaml, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "C:\DEV\01. workspace\korea_wildlife_object_detection\yolov7\models\yolo.py", line 518, in __init__
    self.yaml = yaml.load(f, Loader=yaml.SafeLoader)  # model dict
  File "C:\Users\dlawo\AppData\Roaming\Python\Python310\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "C:\Users\dlawo\AppData\Roaming\Python\Python310\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\dlawo\AppData\Roaming\Python\Python310\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\dlawo\AppData\Roaming\Python\Python310\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Users\dlawo\AppData\Roaming\Python\Python310\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 41: illegal multibyte sequence
[0m
